apiVersion: v1
entries:
  cluster-api-provider-proxmox:
  - annotations:
      cluster.x-k8s.io/provider: proxmox
      cluster.x-k8s.io/v1alpha3: v1alpha3
      cluster.x-k8s.io/v1alpha4: v1alpha4
      cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
    apiVersion: v2
    appVersion: 0.6.0
    created: "2025-08-13T12:45:39.566653528+05:30"
    description: A Helm chart for Cluster API provider proxmox
    digest: 410bf453502c0042dc7c3da0ed78471c94964480a9b24208bc2e790d8a602a5f
    maintainers:
    - name: improwised
    name: cluster-api-provider-proxmox
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/cluster-api-provider-proxmox-0.1.2.tgz
    version: 0.1.2
  - annotations:
      cluster.x-k8s.io/provider: infrastructure-proxmox
      cluster.x-k8s.io/v1alpha3: v1alpha3
      cluster.x-k8s.io/v1alpha4: v1alpha4
      cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
    apiVersion: v2
    appVersion: 0.5.2
    created: "2025-08-13T12:45:39.5669112+05:30"
    description: A Helm chart for Cluster API provider proxmox
    digest: 42ec19adde82fc1d02cdcba87599d47f84f57dba7c1bedadbf8c39a7082bb1b7
    maintainers:
    - name: improwised
    name: cluster-api-provider-proxmox
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/cluster-api-provider-proxmox.tgz
    version: 0.1.1
  proxmox:
  - annotations:
      cluster.x-k8s.io/infrastructure-aws: v1beta1
      cluster.x-k8s.io/provider: infrastructure-aws
    apiVersion: v2
    appVersion: 1.0.3
    created: "2025-08-13T12:45:39.567602492+05:30"
    description: A Helm chart for proxmox
    digest: eafa0f6c5e399863d4b7a7f0a37a9485a202a352888241a9767417582afc895c
    name: proxmox
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/proxmox.tgz
    version: 0.1.8
  talos:
  - annotations:
      cluster.x-k8s.io/provider: infrastructure-proxmox,bootstrap-talos, control-plane-talos
      cluster.x-k8s.io/v1beta1: v1beta1
    apiVersion: v2
    appVersion: 1.4.2
    created: "2025-08-13T12:45:39.567161957+05:30"
    description: A Helm chart for talos
    digest: e22748110de9cfafdba77b92aa522fccd1cbced93c69bea149705fa2b368b12c
    name: talos
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/proxmox-talos.tgz
    version: 0.1.2
  - annotations:
      cluster.x-k8s.io/provider: bootstrap-talos, control-plane-talos
      cluster.x-k8s.io/v1beta1: v1beta1
    apiVersion: v2
    appVersion: 1.4.2
    created: "2025-08-13T12:45:39.568012154+05:30"
    description: A Helm chart for talos
    digest: 4a05a854d63861eede4a3622c1876dafc2734f3142887029aa7ca3a18229bd75
    name: talos
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/talos-0.1.2.tgz
    version: 0.1.2
  - annotations:
      cluster.x-k8s.io/provider: bootstrap-talos, control-plane-talos
      cluster.x-k8s.io/v1beta1: v1beta1
    apiVersion: v2
    appVersion: 1.0.0
    created: "2025-08-13T12:45:39.567797649+05:30"
    description: A Helm chart for talos
    digest: 8dc6cd6f6fd5cef4eeeb5612c7dfa9d8fb56a2440c3d7fae2fc484b99601c66d
    name: talos
    type: application
    urls:
    - https://shivani446.github.io/helm-charts/charts/talos-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-13T12:45:39.566213761+05:30"
